name: Sync dev and master
on: [workflow_dispatch]
  # push:
  #   branches:
  #     - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev5
          target_branch: master
          github_token: ${{ github.token }}
