name: Sync staging and master
on:
  # schedule:
  #   - cron: '0 22 * * *'
  [workflow_dispatch]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: master
          github_token: ${{ github.token }}
